// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: proto/common/kind.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KindType int32

const (
	KindType_UNKNOWN KindType = 0
	KindType_HUMAN   KindType = 1
	KindType_ANIMAL  KindType = 2
	KindType_PLANT   KindType = 3
	KindType_OBJECT  KindType = 4
)

// Enum value maps for KindType.
var (
	KindType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HUMAN",
		2: "ANIMAL",
		3: "PLANT",
		4: "OBJECT",
	}
	KindType_value = map[string]int32{
		"UNKNOWN": 0,
		"HUMAN":   1,
		"ANIMAL":  2,
		"PLANT":   3,
		"OBJECT":  4,
	}
)

func (x KindType) Enum() *KindType {
	p := new(KindType)
	*p = x
	return p
}

func (x KindType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KindType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_kind_proto_enumTypes[0].Descriptor()
}

func (KindType) Type() protoreflect.EnumType {
	return &file_proto_common_kind_proto_enumTypes[0]
}

func (x KindType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KindType.Descriptor instead.
func (KindType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_kind_proto_rawDescGZIP(), []int{0}
}

var File_proto_common_kind_proto protoreflect.FileDescriptor

var file_proto_common_kind_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6b,
	0x69, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x45, 0x0a, 0x08, 0x4b, 0x69, 0x6e, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x48, 0x55, 0x4d, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41,
	0x4e, 0x49, 0x4d, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x4c, 0x41, 0x4e, 0x54,
	0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x04, 0x42, 0x2e,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x72,
	0x6f, 0x31, 0x36, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x64, 0x65, 0x6d,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_common_kind_proto_rawDescOnce sync.Once
	file_proto_common_kind_proto_rawDescData = file_proto_common_kind_proto_rawDesc
)

func file_proto_common_kind_proto_rawDescGZIP() []byte {
	file_proto_common_kind_proto_rawDescOnce.Do(func() {
		file_proto_common_kind_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_kind_proto_rawDescData)
	})
	return file_proto_common_kind_proto_rawDescData
}

var file_proto_common_kind_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_common_kind_proto_goTypes = []interface{}{
	(KindType)(0), // 0: proto.common.KindType
}
var file_proto_common_kind_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_kind_proto_init() }
func file_proto_common_kind_proto_init() {
	if File_proto_common_kind_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_kind_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_kind_proto_goTypes,
		DependencyIndexes: file_proto_common_kind_proto_depIdxs,
		EnumInfos:         file_proto_common_kind_proto_enumTypes,
	}.Build()
	File_proto_common_kind_proto = out.File
	file_proto_common_kind_proto_rawDesc = nil
	file_proto_common_kind_proto_goTypes = nil
	file_proto_common_kind_proto_depIdxs = nil
}
